# Alacritty config
# https://alacritty.org/config-alacritty.html

# Catppuccin mocha theme
# https://github.com/catppuccin/alacritty

[general]
import = [
    #"~/.config/alacritty/catppuccin-mocha.toml"
]


[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }

size = 12.0
